"""add_listing_data_and_assets

Revision ID: 1facbfa43575
Revises: 001
Create Date: 2026-03-23 02:57:43.222424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1facbfa43575'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('dropbox_path', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_listing_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('zillow_beds', sa.Integer(), nullable=True),
    sa.Column('zillow_baths', sa.Float(), nullable=True),
    sa.Column('zillow_sqft', sa.Integer(), nullable=True),
    sa.Column('zillow_year_built', sa.Integer(), nullable=True),
    sa.Column('zillow_price', sa.Integer(), nullable=True),
    sa.Column('zillow_lot_size', sa.String(), nullable=True),
    sa.Column('zillow_property_type', sa.String(), nullable=True),
    sa.Column('realtor_beds', sa.Integer(), nullable=True),
    sa.Column('realtor_baths', sa.Float(), nullable=True),
    sa.Column('realtor_sqft', sa.Integer(), nullable=True),
    sa.Column('realtor_year_built', sa.Integer(), nullable=True),
    sa.Column('realtor_price', sa.Integer(), nullable=True),
    sa.Column('realtor_lot_size', sa.String(), nullable=True),
    sa.Column('realtor_property_type', sa.String(), nullable=True),
    sa.Column('homes_beds', sa.Integer(), nullable=True),
    sa.Column('homes_baths', sa.Float(), nullable=True),
    sa.Column('homes_sqft', sa.Integer(), nullable=True),
    sa.Column('homes_year_built', sa.Integer(), nullable=True),
    sa.Column('homes_price', sa.Integer(), nullable=True),
    sa.Column('homes_lot_size', sa.String(), nullable=True),
    sa.Column('homes_property_type', sa.String(), nullable=True),
    sa.Column('beds', sa.Integer(), nullable=True),
    sa.Column('baths', sa.Float(), nullable=True),
    sa.Column('sqft', sa.Integer(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('lot_size', sa.String(), nullable=True),
    sa.Column('property_type', sa.String(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('confidence_notes', sa.String(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', name='uq_listing_data_project')
    )
    # ### end Alembic commands ###
    # Data migration: rename existing 'exterior' room_tag to 'exterior_front'
    op.execute("UPDATE photos SET room_tag = 'exterior_front' WHERE room_tag = 'exterior'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_listing_data')
    op.drop_table('project_assets')
    # ### end Alembic commands ###
    op.execute("UPDATE photos SET room_tag = 'exterior' WHERE room_tag = 'exterior_front'")
